---
title: "online_retail_case"
author: "Mauricio Ferreira"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(BTYD)
library(BTYDplus)
library(dplyr)
```

```{r}
df.import<- read.csv("C:/Users/Qvista/Documents/Customer Lifetime Value/Online Retail.csv", header=TRUE, sep="," )
```

```{r}
df<- df.import %>%
  mutate(sales = as.numeric(as.character(Quantity)) * as.numeric(as.character(UnitPrice))) %>%
  select(CustomerID, InvoiceDate, sales)

# for (i in 1:nrow(df)){
#   df$Date  <- strsplit(as.character(df$InvoiceDate)," ")[[1]]
# }

new.df<- df %>% 
    tidyr::separate(InvoiceDate,                      
                    c("Month", "Day","Year"),
                    extra='drop') %>%
    tidyr::unite('date',c('Year','Month', 'Day'), sep = "-") %>%
    rename(cust = CustomerID) %>%
    mutate(len = nchar(date))

clean.df<-new.df %>%
  filter(len==9 | len==10) %>%
  select(-len)


cna <- grep("NA", clean.df$date)
clean.df<- clean.df[-cna,]

#new.df$Date <- as.Date(new.df$Date, "%Y%m%d")

head(clean.df)
```


This function returns an event log
with only one transaction per customer per day, with the total sum of their
spending for that day as the sales number.

```{r}
elog <- dc.MergeTransactionsOnSameDate(clean.df);
head(elog)

end.of.cal.period <- as.Date("2011-4-30")
elog.cal <- elog[which(elog$date <= end.of.cal.period), ]

split.data <- dc.SplitUpElogForRepeatTrans(elog.cal);
clean.elog <- split.data$repeat.trans.elog;
```

```{r}
freq.cbt <- dc.CreateFreqCBT(clean.elog);
freq.cbt[1:3,1:5]


```

```{r}
tot.cbt <- dc.CreateFreqCBT(elog)
cal.cbt <- dc.MergeCustomers(tot.cbt, freq.cbt)

birth.periods <- split.data$cust.data$birth.per
last.dates <- split.data$cust.data$last.date
cal.cbs.dates <- data.frame(birth.periods, last.dates,
end.of.cal.period)
cal.cbs <- dc.BuildCBSFromCBTAndDates(cal.cbt, cal.cbs.dates,
per="week")

cal.cbs<- as.data.frame(cal.cbs) %>%
  filter(t.x > 0)


params <- pnbd.EstimateParameters(cal.cbs);
params

LL <- pnbd.cbs.LL(params, cal.cbs);
LL

```

```{r}
p.matrix <- c(params, LL);
for (i in 1:2){
params <- pnbd.EstimateParameters(cal.cbs, params);
LL <- pnbd.cbs.LL(params, cal.cbs);
p.matrix.row <- c(params, LL);
p.matrix <- rbind(p.matrix, p.matrix.row);
}
colnames(p.matrix) <- c("r", "alpha", "s", "beta", "LL");
rownames(p.matrix) <- 1:3;
p.matrix;

```

```{r}

pnbd.Expectation(params, t=52);
```

```{r}
cal.cbs["1516",]

x <- cal.cbs["1516", "x"]
t.x <- cal.cbs["1516", "t.x"]
T.cal <- cal.cbs["1516", "T.cal"]
pnbd.ConditionalExpectedTransactions(params, T.star = 52,
x, t.x, T.cal)
# [1] 25.46
pnbd.PAlive(params, x, t.x, T.cal)

```

```{r}
for (i in seq(10, 25, 5)){
cond.expectation <- pnbd.ConditionalExpectedTransactions(
params, T.star = 52, x = i,
t.x = 20, T.cal = 39) 
cat ("x:",i,"\t Expectation:",cond.expectation, fill = TRUE)
}

```


```{r}
pnbd.PlotFrequencyInCalibration(params, cal.cbs, 7)
```


```{r}
elog <- dc.SplitUpElogForRepeatTrans(elog)$repeat.trans.elog;
x.star <- rep(0, nrow(cal.cbs));
cal.cbs <- cbind(cal.cbs, x.star);
elog.custs <- elog$cust;
for (i in 1:nrow(cal.cbs)){
current.cust <- rownames(cal.cbs)[i]
tot.cust.trans <- length(which(elog.custs == current.cust))
cal.trans <- cal.cbs[i, "x"]
cal.cbs[i, "x.star"] <- tot.cust.trans - cal.trans
}
cal.cbs[1:3,]

```

```{r}
T.star <- 39 # length of the holdout period
censor <- 7 # This censor serves the same purpose described above
x.star <- cal.cbs[,"x.star"]
comp <- pnbd.PlotFreqVsConditionalExpectedFrequency(params, T.star,
cal.cbs, x.star, censor)
```

